# Generated by Django 4.1 on 2022-12-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="inference", name="kgv",),
        migrations.AddField(
            model_name="inference",
            name="logo",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
