# Generated by Django 4.1 on 2022-12-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_remove_inference_kgv_inference_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inference", name="score", field=models.IntegerField(),
        ),
    ]
