# Generated by Django 4.1 on 2023-01-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0003_alter_inference_score"),
    ]

    operations = [
        migrations.RemoveField(model_name="inference", name="market",),
        migrations.AddField(
            model_name="inference", name="kgv", field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="inference",
            name="mcap",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="inference",
            name="wsb_rel",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="inference",
            name="score",
            field=models.IntegerField(default=None),
        ),
    ]
