# Generated by Django 4.1 on 2023-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_app",
            "0004_remove_inference_market_inference_kgv_inference_mcap_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inference",
            name="market",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
