# Generated by Django 4.1 on 2023-01-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0007_alter_inference_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inference",
            name="score",
            field=models.IntegerField(default=None),
        ),
    ]
