# Generated by Django 4.1 on 2023-01-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0008_alter_inference_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="inference",
            name="gross_margins",
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="inference", name="kgv", field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="inference",
            name="long_name",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="inference",
            name="mcap",
            field=models.IntegerField(default=None),
        ),
    ]
