# Generated by Django 4.1 on 2023-01-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0009_inference_gross_margins_inference_kgv_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="inference", name="kgv",),
    ]
