# Generated by Django 4.1 on 2023-01-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0011_remove_inference_gross_margins_remove_inference_mcap"),
    ]

    operations = [
        migrations.AddField(
            model_name="inference", name="mcap", field=models.IntegerField(null=True),
        ),
    ]
