# Generated by Django 4.1 on 2023-01-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0012_inference_mcap"),
    ]

    operations = [
        migrations.AddField(
            model_name="inference",
            name="gross_margins",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="inference", name="kgv", field=models.FloatField(null=True),
        ),
    ]
