# Generated by Django 4.1.5 on 2023-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_inference_gross_margins_inference_kgv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inference',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inference',
            name='long_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inference',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inference',
            name='stock_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inference',
            name='wsb_rel',
            field=models.FloatField(null=True),
        ),
    ]
